[package]
authors = ["Alessandro Rosetti <alessandro.rosetti@gmail.com>"]
name = "katas_and_snippets"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.11.0"
regex = "1.7.1"
num = "0.4.0"
time = "0.3.23"
derive_builder = "0.12.0"
nom = "7.1.3"
