services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: hackernews
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
