apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: roarc/gotmpl-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: staging
        - name: LISTEN_PORT
          value: "8080"
        - name: DB_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
        - name: DB_PORT
          value: "27017"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000 # must be in range 30000-32767
