package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"

	"github.com/roarc0/jobs/graph/model"
)

// CreateJobListing is the resolver for the createJobListing field.
func (r *mutationResolver) CreateJobListing(ctx context.Context, input model.CreateJobListingInput) (*model.JobListing, error) {
	ctx, cancel := context.WithTimeout(ctx, r.timeoutDuration)
	defer cancel()
	return r.db.CreateJobListing(ctx, input)
}

// UpdateJobListing is the resolver for the updateJobListing field.
func (r *mutationResolver) UpdateJobListing(ctx context.Context, id string, input model.UpdateJobListingInput) (*model.JobListing, error) {
	ctx, cancel := context.WithTimeout(ctx, r.timeoutDuration)
	defer cancel()
	return r.db.UpdateJobListing(ctx, id, input)
}

// DeleteJobListing is the resolver for the deleteJobListing field.
func (r *mutationResolver) DeleteJobListing(ctx context.Context, id string) (*model.DeleteJobResponse, error) {
	ctx, cancel := context.WithTimeout(ctx, r.timeoutDuration)
	defer cancel()
	return r.db.DeleteJobListing(ctx, id)
}

// Jobs is the resolver for the jobs field.
func (r *queryResolver) Jobs(ctx context.Context) ([]*model.JobListing, error) {
	ctx, cancel := context.WithTimeout(ctx, r.timeoutDuration)
	defer cancel()
	return r.db.GetJobs(ctx)
}

// Job is the resolver for the job field.
func (r *queryResolver) Job(ctx context.Context, id string) (*model.JobListing, error) {
	ctx, cancel := context.WithTimeout(ctx, r.timeoutDuration)
	defer cancel()
	return r.db.GetJob(ctx, id)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
